### ISSUE TITLE
Angular 9 support

### ISSUE THREAD

**Issue by Rogier-blip** [orjandesmet/ngx-library-assets#4]
He there,

I have a question, does this library support Angular 9 workspaces?

Cheers

**Comment by oliver-luschnitz** [comment]
Hello,

I've got the same question :-)

Regards

**Comment by orjandesmet** [comment]
Hi, yes it does support Angular9. I haven’t tested Angular 10 yet, but I believe it should work too.

**Comment by Rogier-blip** [comment]
Hee, thanks for your response :)

I also found that it works, but if you don't explicitly set in the package.json that the Angular version is e.g. version 9 then `ng update` will complain that you are trying to update with a package that does not support this Angular version.

**Comment by orjandesmet** [comment]
> Hee, thanks for your response :)
> 
> I also found that it works, but if you don't explicitly set in the package.json that the Angular version is e.g. version 9 then `ng update` will complain that you are trying to update with a package that does not support this Angular version.

You are absolutely correct. So I've published two new versions:

* 1.1.0 with support for Angular9
* 1.2.0 with support for Angular10
